# Functions
## Math
Ce Notebook répertorie toutes les fonctions du dossier _Math_ issu de _Functions_.

In [ ]:
def normalizeVect(v):
    import numpy as np
    norm = np.linalg.norm(v)
    if norm == 0:
        return v
    return v / norm

In [33]:
import numpy as np
a = np.array([1,0,0,0])

In [20]:
def quat2rot(q):
    import numpy as np
    return np.transpose(np.array([ \
                             [1-2*q[1]**2-2*q[2]**2, \
                             2*(q[0]*q[1] + q[2]*q[3]), \
                             2*(q[0]*q[2] - q[1]*q[3])], \
                             [2*(q[0]*q[1] - q[2]*q[3]), \
                             1-2*q[0]**2-2*q[2]**2, \
                             2*(q[1]*q[2] + q[0]*q[3])], \
                             [2*(q[0]*q[2] + q[1]*q[3]), \
                             2*(q[1]*q[2] - q[0]*q[3]), \
                             1-2*q[0]**2 - 2*q[1]**2]]))

In [22]:
b = np.array([ \
                             [1-2*1**2-2*2**2, \
                             2, \
                             6], \
                             [12, \
                             -7, \
                             4], \
                             [6, \
                             4, \
                             -3]])

In [23]:
b

array([[-9,  2,  6],
       [12, -7,  4],
       [ 6,  4, -3]])

In [24]:
len(b)

3

In [25]:
len(b[0])

3

In [26]:
b[2]

array([ 6,  4, -3])

In [27]:
b[1][0]

12

In [34]:
quat2rot(a)

array([[ 1,  0,  0],
       [ 0, -1,  0],
       [ 0,  0, -1]])

In [17]:
len(a)

3

In [29]:
len(a[0])

3